name: desktop_im
description: "A IM Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # sqlite3: ^2.0.0 # 使用Hive代替
  path_provider: ^2.0.0

  # provider: ^6.0.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  hive: ^2.2.3 # 数据持久化
  hive_flutter: ^1.1.0 # 提供了与 Flutter 集成的特定功能
  
  dio: 5.4.0
  logger: 2.0.2
  flutter_toastr: ^1.0.3
  json_annotation: ^4.8.1
  flutter_gen: ^5.0.0

  badges: ^2.0.2
  tuple: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  # shared_preferences: ^2.2.2 # 用hive代替
  build_runner: ^2.4.8 # 用于执行生成器
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  
flutter_intl:
  enabled: true

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
 
# #颜色相关
#   colors:
#     enabled: true
# #颜色输出路径
#       class_name: ComeinColor
# #颜色原文件路径
#     inputs:
#       - assets/color/colors.xml
